server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/HydotCommerceSys
    username: root
    password: HydotTech
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: mail.hydottech.com
    port: 465
    username: customers@hydottech.com
    password: SolDanKoHy1
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  servlet:
    multipart:
      max-file-size: -1  # Maximum size of a single file
      max-request-size: -1  # Maximum total request size (including form data)
  web:
    resources:
      add-mappings: true
      static-path-pattern: /uploads/**
